# Change these first
owner: kamleshpaul # Your GitHub organization or username, where this repository lives
repo: codingtricks.co-uptime # The name of this repository

sites:
  - name: Codingtricks
    url: https://codingtricks.co/
    
assignees:
  - Kamleshpaul

status-website:
  baseUrl:  https://kamleshpaul.github.io/codingtricks.co-uptime/
  name: Codingtricks
